'use strict'

const keyTokenModel = require("../models/keyToken.model");
class KeyTokenService {
// write  function create token:
static createKeyToken = async ({userId, publicKey, privateKey}) =>{
    try{

        // publicKey -> is generated by the asynmmetrict algorithm -> so which has type data buffer( it's not hash ) 
        // transfer the type data( buffer ) to String and saving it in DB (Because if web save type data( buffer ) in DB we will get the error)

      //  const publicKeyString = publicKey.toString();
      //  const cleanPublicKeyString = publicKeyString.replace("-----BEGIN RSA PUBLIC KEY-----", "").replace("-----END RSA PUBLIC KEY-----", "").trim();

        const token = await keyTokenModel.create({
            user: userId,
            publicKey: publicKey,
            privateKey: privateKey
        })

        return token ? token.publicKey : null;
    }catch(error){
        return error;
    }
}

}

module.exports = KeyTokenService; // because use static function so web just export a class ( not a new instance's class )