### signup
POST http://localhost:5000/v1/api/shop/signup
Content-Type: application/json

{
    "name": "shop vanh",
    "email": "shopTip02@gmail.com",
    "password": "123456789"
}


// tạo một cái request khác có chứa headers (xử lý middleware bên trong):
### signup
POST http://localhost:5000/v1/api/shop/signup
Content-Type: application/json
x-api-key: 6239241f841ddfffb01250b07b3dfbda3b596c93264a6ec03269ba35653f5d15f68e8df8e91d0a72530cb3af23f139fdb8336fcee2f64287417e9add96f363dc

{
    "name": "shop vanh",
    "email": "shopTip08@gmail.com",
    "password": "123456789"
}

// login:
### login
POST http://localhost:5000/v1/api/shop/login
Content-Type: application/json
x-api-key: 6239241f841ddfffb01250b07b3dfbda3b596c93264a6ec03269ba35653f5d15f68e8df8e91d0a72530cb3af23f139fdb8336fcee2f64287417e9add96f363dc

{
    "email": "shopTip08@gmail.com",
    "password": "123456789"
}


// logout:
### logout
POST http://localhost:5000/v1/api/shop/logout
Content-Type: application/json
x-api-key: 6239241f841ddfffb01250b07b3dfbda3b596c93264a6ec03269ba35653f5d15f68e8df8e91d0a72530cb3af23f139fdb8336fcee2f64287417e9add96f363dc
x-client-id: 6561879dfb0e542382ad7dd7
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOiI2NTYxODc5ZGZiMGU1NDIzODJhZDdkZDciLCJlbWFpbCI6InNob3BUaXAwOEBnbWFpbC5jb20iLCJyb2xlcyI6IlNIT1AiLCJpYXQiOjE3MDA4OTE0OTUsImV4cCI6MTcwMTA2NDI5NX0.7RJnk14NmL6CbhlwCc8Xz7TelA-FpnNUydcPofD_mYE

{
}