### signup
POST http://localhost:5000/v1/api/shop/signup
Content-Type: application/json

{
    "name": "shop vanh",
    "email": "shopTip02@gmail.com",
    "password": "123456789"
}


// tạo một cái request khác có chứa headers (xử lý middleware bên trong):
### signup
POST http://localhost:5000/v1/api/shop/signup
Content-Type: application/json
x-api-key: 6239241f841ddfffb01250b07b3dfbda3b596c93264a6ec03269ba35653f5d15f68e8df8e91d0a72530cb3af23f139fdb8336fcee2f64287417e9add96f363dc

{
    "name": "shop vanh",
    "email": "shopTip08@gmail.com",
    "password": "123456789"
}

// login:
### login
POST http://localhost:5000/v1/api/shop/login
Content-Type: application/json
x-api-key: 6239241f841ddfffb01250b07b3dfbda3b596c93264a6ec03269ba35653f5d15f68e8df8e91d0a72530cb3af23f139fdb8336fcee2f64287417e9add96f363dc

{
    "email": "shopTip08@gmail.com",
    "password": "123456789"
}

// refreshToken FOR VERSION 1:
### refreshToken
POST http://localhost:5000/v1/api/shop/refreshToken
Content-Type: application/json
x-api-key: 6239241f841ddfffb01250b07b3dfbda3b596c93264a6ec03269ba35653f5d15f68e8df8e91d0a72530cb3af23f139fdb8336fcee2f64287417e9add96f363dc
x-client-id: 6561879dfb0e542382ad7dd7
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOiI2NTYxODc5ZGZiMGU1NDIzODJhZDdkZDciLCJlbWFpbCI6InNob3BUaXAwOEBnbWFpbC5jb20iLCJyb2xlcyI6IlNIT1AiLCJpYXQiOjE3MDExMzM1MDMsImV4cCI6MTcwMTMwNjMwM30.3w7sA7S9_My8hwF6MhDnlNaxNAofRCTE-g0WU2qNsWI

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOiI2NTYxODc5ZGZiMGU1NDIzODJhZDdkZDciLCJlbWFpbCI6InNob3BUaXAwOEBnbWFpbC5jb20iLCJyb2xlcyI6IlNIT1AiLCJpYXQiOjE3MDExMzM1MDMsImV4cCI6MTcwMTczODMwM30.D253IC8ULWeW8PXH2KKFTJbVVYI1RmyJJNWYc626LW0"
}

### refreshToken FOR VERSION 2:
POST http://localhost:5000/v1/api/shop/refreshToken
Content-Type: application/json
x-api-key: 6239241f841ddfffb01250b07b3dfbda3b596c93264a6ec03269ba35653f5d15f68e8df8e91d0a72530cb3af23f139fdb8336fcee2f64287417e9add96f363dc
x-client-id: 6561879dfb0e542382ad7dd7
refreshtoken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOiI2NTYxODc5ZGZiMGU1NDIzODJhZDdkZDciLCJlbWFpbCI6InNob3BUaXAwOEBnbWFpbC5jb20iLCJyb2xlcyI6IlNIT1AiLCJpYXQiOjE3MDExMzY4OTIsImV4cCI6MTcwMTc0MTY5Mn0.g_MedLv1DYZNDItmLXd4jbr7TfIIvDjhd9eavxlBAYQ

{
   
}




// logout:
### logout
POST http://localhost:5000/v1/api/shop/logout
Content-Type: application/json
x-api-key: 6239241f841ddfffb01250b07b3dfbda3b596c93264a6ec03269ba35653f5d15f68e8df8e91d0a72530cb3af23f139fdb8336fcee2f64287417e9add96f363dc
x-client-id: 6561879dfb0e542382ad7dd7
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOiI2NTYxODc5ZGZiMGU1NDIzODJhZDdkZDciLCJlbWFpbCI6InNob3BUaXAwOEBnbWFpbC5jb20iLCJyb2xlcyI6IlNIT1AiLCJpYXQiOjE3MDExODgwOTUsImV4cCI6MTcwMTM2MDg5NX0.6U0nS7Gn-MwL5UDz2yT96VpZd-o5MqDUl-Yyiv8jEzo

{
}

// Create Product section 12:
### Create_Product
POST http://localhost:5000/v1/api/shop/create/product
Content-Type: application/json
x-api-key: 6239241f841ddfffb01250b07b3dfbda3b596c93264a6ec03269ba35653f5d15f68e8df8e91d0a72530cb3af23f139fdb8336fcee2f64287417e9add96f363dc
x-client-id: 6561879dfb0e542382ad7dd7
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOiI2NTYxODc5ZGZiMGU1NDIzODJhZDdkZDciLCJlbWFpbCI6InNob3BUaXAwOEBnbWFpbC5jb20iLCJyb2xlcyI6IlNIT1AiLCJpYXQiOjE3MDExODgwOTUsImV4cCI6MTcwMTM2MDg5NX0.6U0nS7Gn-MwL5UDz2yT96VpZd-o5MqDUl-Yyiv8jEzo

{
    "product_name": "new_jeans",
    "product_thumb": "https://assemblylabel.com/cdn/shop/products/c01a596fd3cb4413bad785724b510096_600x.jpg?v=1693190679",
    "product_description": "high quantity and perfect",
    "product_price": 50,
    "product_quantity": 5,
    "product_type": "Clothing",
    "product_shop": "6561879dfb0e542382ad7dd7",
    "product_attributes": {
        "brand": "Levis",
        "size": "L",
        "material": "demin"
    }
}
